name: Create Pull Request with API Data

on:
  workflow_dispatch:  # GitHub上のGUIからトリガー可能

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Fetch Notion data and create Markdown
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
        run: |
          node fetchNotion.js "$NOTION_API_KEY" "$NOTION_DB_ID"
          node makeMarkdown.js "$NOTION_API_KEY"

      - name: Read updated page titles
        id: read_titles
        run: |
          UPDATED_TITLES=$(cat updated_titles.txt)
          echo "UPDATED_TITLES<<EOF" >> $GITHUB_OUTPUT
          echo "$UPDATED_TITLES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update gha-test.md with API data
          title: Update gha-test.md with API data
          body: |

            Updated pages:
            ${{ steps.read_titles.outputs.UPDATED_TITLES }}
          branch: update-gha-test-api-data
