name: Create Pull Request with API Data

on:
  workflow_dispatch:  # GitHub上のGUIからトリガー可能

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Fetch Notion data and create Markdown
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
        run: |
          node fetchNotion.js "$NOTION_API_KEY" "$NOTION_DB_ID"
          node makeMarkdown.js "$NOTION_API_KEY"

      - name: Get changed files
        id: changed_files
        run: |
          git add .
          git diff --cached --name-only > changed_files.txt
          if [ -s changed_files.txt ]; then
            echo "CHANGED_FILES<<EOF" >> $GITHUB_OUTPUT
            cat changed_files.txt >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "CHANGED_FILES=No files were changed" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update files with API data
          title: Update files with API data
          body: |
            Updated files:
            ${{ steps.changed_files.outputs.CHANGED_FILES }}
          branch: update-api-data
